theme: jekyll-theme-architect

title: [uel-ri]
description: [Unified Expression Language]

# sidebar links url
links:
  source: https://github.com/javaee/uel-ri
  #download:
  #mailinglist:
  #javadocs:
  #docs:
  #faq:
  #mailinglist:
  #hide_issuetracker: true #set explicitly to 'true' if you don't want to have the issue tracker link displayed

